# Disclaimer: File was origonaly generated by Claude to quickly convert from previous config layout to new one.
# - Verified working and modified to its current state by xvr6

# File icons for nvim-web-devicons (used by neo-tree, bufferline, telescope, ...)
# and for neo-tree's folders. Glyphs are Nerd Font code points.
{ lib, ... }:
let
  # folder = "";
  # used for files that match nothing below
  file = "";

  # Keyed by extension, without the dot. Dotfiles resolve here too
  # (`.gitignore` -> `gitignore`), see `dotfiles` below.
  extensions = {
    # Languages, configs and documents
    styl = "";
    sass = "";
    scss = "";
    htm = "";
    html = "";
    slim = "";
    haml = "";
    ejs = "";
    css = "";
    less = "";
    md = "";
    mdx = "";
    markdown = "";
    rmd = "";
    json = "";
    webmanifest = "";
    js = "";
    mjs = "";
    jsx = "";
    rb = "";
    gemspec = "";
    rake = "";
    php = "";
    py = "";
    pyc = "";
    pyo = "";
    pyd = "";
    coffee = "";
    mustache = "";
    hbs = "";
    conf = "";
    ini = "";
    yml = "";
    yaml = "";
    toml = "";
    bat = "";
    mk = "";
    twig = "";
    cpp = "";
    "c++" = "";
    cxx = "";
    cc = "";
    cp = "";
    c = "";
    cs = "󰌛";
    h = "";
    hh = "";
    hpp = "";
    hxx = "";
    hs = "";
    lhs = "";
    nix = "";
    lua = "";
    java = "";
    sh = "";
    fish = "";
    bash = "";
    zsh = "";
    ksh = "";
    csh = "";
    awk = "";
    ps1 = "";
    ml = "λ";
    mli = "λ";
    diff = "";
    db = "";
    sql = "";
    dump = "";
    clj = "";
    cljc = "";
    cljs = "";
    edn = "";
    scala = "";
    go = "";
    dart = "";
    xul = "";
    sln = "";
    suo = "";
    pl = "";
    pm = "";
    t = "";
    rss = "";
    "f#" = "";
    fsscript = "";
    fsx = "";
    fs = "";
    fsi = "";
    rs = "";
    rlib = "";
    d = "";
    erl = "";
    hrl = "";
    ex = "";
    exs = "";
    eex = "";
    leex = "";
    heex = "";
    vim = "";
    ai = "";
    psd = "";
    psb = "";
    ts = "";
    tsx = "";
    jl = "";
    pp = "";
    vue = "";
    elm = "";
    swift = "";
    xcplayground = "";
    tex = "󰙩";
    r = "󰟔";
    rproj = "󰗆";
    sol = "󰡪";
    pem = "󰇱";

    # Well-known files
    ds_store = "";
    gitconfig = "";
    gitignore = "";
    gitattributes = "";
    bashrc = "";
    zshrc = "";
    zshenv = "";
    zprofile = "";
    vimrc = "";
    gvimrc = "";
    bashprofile = "";

    # Archives
    tar = "";
    tgz = "";
    arc = "";
    arj = "";
    taz = "";
    lha = "";
    lz4 = "";
    lzh = "";
    lzma = "";
    tlz = "";
    txz = "";
    tzo = "";
    t7z = "";
    zip = "";
    z = "";
    dz = "";
    gz = "";
    lrz = "";
    lz = "";
    lzo = "";
    xz = "";
    zst = "";
    tzst = "";
    bz2 = "";
    bz = "";
    tbz = "";
    tbz2 = "";
    tz = "";
    deb = "";
    rpm = "";
    jar = "";
    war = "";
    ear = "";
    sar = "";
    rar = "";
    alz = "";
    ace = "";
    zoo = "";
    cpio = "";
    "7z" = "";
    rz = "";
    cab = "";
    wim = "";
    swm = "";
    dwm = "";
    esd = "";

    # Images
    jpg = "";
    jpeg = "";
    jpe = "";
    jfif = "";
    pjpeg = "";
    png = "";
    apng = "";
    gif = "󰵸";
    bmp = "";
    tga = "";
    tif = "";
    tiff = "";
    pcx = "";
    webp = "";
    avif = "";
    heic = "";
    heif = "";
    jxl = "";
    jp2 = "";
    j2k = "";
    ico = "";
    pbm = "";
    pgm = "";
    ppm = "";
    xbm = "";
    xpm = "";

    # Images: vector
    svg = "";
    svgz = "";
    emf = "";
    cgm = "";
    xcf = "";
    kra = "";
    mng = "";
    xwd = "";
    yuv = "";

    # Images: camera raw
    raw = "󱨏";
    dng = "󱨏";
    cr2 = "󱨏";
    cr3 = "󱨏";
    nef = "󱨏";
    arw = "󱨏";
    orf = "󱨏";
    rw2 = "󱨏";
    raf = "󱨏";

    # Video
    mp4 = "󱜐";
    m4v = "󰈫";
    mp4v = "󰈫";
    mkv = "󱛽";
    webm = "󱜐";
    mov = "󱜐";
    qt = "󰈫";
    avi = "󰈫";
    wmv = "󰈫";
    asf = "󰈫";
    flv = "󰈫";
    f4v = "󰈫";
    mpg = "󰈫";
    mpeg = "󰈫";
    mpe = "󰈫";
    m2v = "󰈫";
    mpv = "󰈫";
    mts = "󰈫";
    m2ts = "󰈫";
    "3gp" = "󰈫";
    "3g2" = "󰈫";
    ogv = "󰈫";
    ogm = "󰈫";
    ogx = "󰈫";
    vob = "󰈫";
    divx = "󰈫";
    rm = "󰈫";
    rmvb = "󰈫";
    nuv = "󰈫";
    mxf = "󰈫";
    mjpg = "󰈫";
    mjpeg = "󰈫";
    flc = "󰈫";
    fli = "󰈫";
    gl = "󰈫";
    dl = "󰈫";

    # Audio
    mp3 = "";
    mp2 = "";
    aac = "";
    m4a = "";
    m4b = "";
    m4r = "";
    flac = "";
    alac = "";
    ogg = "";
    oga = "";
    opus = "";
    spx = "";
    wav = "󱑽";
    aif = "";
    aiff = "";
    au = "";
    wma = "";
    wv = "";
    ape = "";
    amr = "";
    weba = "";
    mka = "";
    mid = "";
    midi = "";
    mpc = "";
    ra = "";
    xspf = "";

    # Other
    pdf = "";
  };

  # Keyed by full filename.
  filenames = {
    # Well-known files
    "gruntfile.coffee" = "";
    "gruntfile.js" = "";
    "gruntfile.ls" = "";
    "gulpfile.coffee" = "";
    "gulpfile.js" = "";
    "gulpfile.ls" = "";
    "mix.lock" = "";
    "flake.lock" = "";
    dropbox = "";
    ".gitlab-ci.yml" = "";
    _vimrc = "";
    _gvimrc = "";
    "favicon.ico" = "";
    license = "";
    node_modules = "";
    "react.jsx" = "";
    procfile = "";
    dockerfile = "";
    "docker-compose.yml" = "";
    "docker-compose.yaml" = "";
    "compose.yml" = "";
    "compose.yaml" = "";
    rakefile = "";
    "config.ru" = "";
    gemfile = "";
    makefile = "";
    "cmakelists.txt" = "";
    "robots.txt" = "󰚩";
    "go.mod" = "";

    # Bundled and minified files
    "jquery.min.js" = "";
    "angular.min.js" = "";
    "backbone.min.js" = "";
    "require.min.js" = "";
    "materialize.min.js" = "";
    "materialize.min.css" = "";
    "mootools.min.js" = "";
    vimrc = "";
    vagrantfile = "";
  };

  # devicons checks full filenames before extensions and ships filename entries
  # for some dotfiles (.gitignore, .bashrc, ...), which would shadow the extension
  # entries above. Re-register dotfiles as filenames, but only where one exists.
  dotfiles = lib.mapAttrs' (ext: glyph: lib.nameValuePair ".${ext}" glyph) extensions;

  # An override replaces the whole devicons entry, so carry over the stock
  # color/name where one exists and only swap the glyph.
  overrides =
    {
      always,
      onlyIfKnown ? { },
    }:
    {
      __raw = ''
        (function()
          local base = require("nvim-web-devicons").get_icons()
          local out = {}
          local function add(entries, only_known)
            for key, glyph in pairs(entries) do
              local orig = base[key]
              if orig or not only_known then
                orig = orig or {}
                out[key] = {
                  icon = glyph,
                  color = orig.color or "#6d8086",
                  cterm_color = orig.cterm_color or "66",
                  name = orig.name or "Default",
                }
              end
            end
          end
          add(${lib.nixvim.toLuaObject always}, false)
          add(${lib.nixvim.toLuaObject onlyIfKnown}, true)
          return out
        end)()
      '';
    };
in
{
  plugins.web-devicons.settings = {
    override_by_extension = overrides { always = extensions; };
    override_by_filename = overrides {
      always = filenames;
      onlyIfKnown = dotfiles;
    };
    override.default_icon = {
      icon = file;
      color = "#6d8086";
      cterm_color = "66";
      name = "Default";
    };
  };
}
